[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "magneticsolver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "einops>=0.8.1",
    "numpy>=2.0.2",
    "scipy>=1.13.1",
]
